name: Reddit Data Pipeline

on:
  schedule:
    - cron: '19 22 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Prefect flow
      run: |
        python run_pipeline.py 2>&1 | tee pipeline_output.log

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs
        path: pipeline_output.log

    - name: Upload data artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reddit-data
        path: data/
        retention-days: 7
