name: Reddit Data Pipeline

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 21 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug: List files
      run: |
        echo "Root directory contents:"
        ls -la
        echo "python_scripts contents:"
        ls -la python_scripts
        
    - name: Run Prefect flow
      run: |
        python run_pipeline.py 2>&1 | tee ../pipeline_output.log

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs
        path: pipeline_output.log
        
    - name: Upload data artifacts
      if: always()  # Run even if previous steps fail
      uses: actions/upload-artifact@v4 
      with:
        name: reddit-data
        path: data/
        retention-days: 7