name: Reddit Data Pipeline

on:
  schedule:
    - cron: '40 9 * * *'
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Prefect flow
      run: |
        python run_pipeline.py 2>&1 | tee pipeline_output.log

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pipeline-logs
        path: pipeline_output.log

    - name: Prepare latest raw CSV for upload
      if: always()
      run: |
        LATEST_FILE=$(ls -t data/raw/*.csv | head -n 1)
        echo "Latest file: $LATEST_FILE"
        mkdir -p temp_upload
        cp "$LATEST_FILE" temp_upload/
      shell: bash

    - name: Upload latest raw CSV only
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reddit-latest-raw
        path: temp_upload/
        retention-days: 7

    - name: Commit and Push New Raw Data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        git pull origin ${{ github.ref_name }}
        git add data/raw/

        if git diff --cached --quiet; then
          echo "No changes in data/raw/ to commit."
        else
          git commit -m "🔄 Add new raw Reddit data [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push origin ${{ github.ref_name }}
        fi
      env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com
        GIT_COMMITTER_NAME: github-actions
        GIT_COMMITTER_EMAIL: github-actions@github.com
